#!/bin/bash

set -e

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

export SHARDS_CACHE_PATH="$DIR/vendor/cache/shards"

if $GITHUB_ACTIONS; then
  export SHARDS_CACHE_PATH="$HOME/.cache/shards"
fi

shards install --local
